from flask import Flask, render_template, request, send_file, redirect, url_for
from tensorflow.keras.utils import load_img
from keras_preprocessing.image import img_to_array
from keras.models import load_model
import numpy as np
import io
import datetime
from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle,
    ListFlowable, ListItem
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

app = Flask(__name__)
Model_Path = 'models/Pneumonia_Model.h5'
model = load_model(Model_Path)

# نخزن آخر نتيجة مؤقتًا
last_prediction = {"label": None, "confidence": None, "imagePath": None, "details": None, "timestamp": None}


@app.route('/', methods=['GET'])
def home():
    return render_template("index.html")


@app.route('/', methods=['POST'])
def predict():
    global last_prediction
    imagefile = request.files["imagefile"]
    image_path = './static/' + imagefile.filename
    imagefile.save(image_path)

    img = load_img(image_path, target_size=(256, 256))
    x = img_to_array(img)
    x = x / 255.0
    x = np.expand_dims(x, axis=0)

    classes = model.predict(x)
    prob = float(classes[0][0])
    label = "Positive" if prob >= 0.5 else "Negative"

    confidence = round(prob * 100, 2)

    # تفاصيل
    details = f"""
    تم تحميل الصورة ومعالجتها (256x256 بكسل).
    تم تحويل الصورة إلى مصفوفة رقمية وتطبيعها.
    النموذج (CNN) حلل خصائص الأشعة السينية.
    النتيجة: {label}.
    نسبة الثقة: {confidence}% .
    """

    last_prediction["label"] = label
    last_prediction["confidence"] = confidence
    last_prediction["imagePath"] = image_path
    last_prediction["details"] = details
    last_prediction["timestamp"] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    return render_template(
        'index.html',
        prediction_label=label,
        prediction_confidence=confidence,
        imagePath=image_path,
        details=details,
        timestamp=last_prediction["timestamp"]
    )


@app.route('/download_report')
def download_report():
    if not last_prediction["label"]:
        return redirect(url_for('home'))

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    # العنوان
    elements.append(Paragraph("📄 Medical Report - Pneumonia Detector", styles['Title']))
    elements.append(Spacer(1, 20))

    # جدول البيانات الأساسية
    data = [
        ["Diagnosis Result:", last_prediction['label']],
        ["Infection Rate:", f"{last_prediction['confidence']}%"],
        ["Examination Date:", last_prediction['timestamp']]
    ]
    table = Table(data, colWidths=[150, 300])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("BOX", (0, 0), (-1, -1), 1, colors.black),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 20))

    

    # صورة الأشعة
    if last_prediction["imagePath"]:
        try:
            elements.append(Paragraph("Chest X-ray Image:", styles['Heading2']))
            elements.append(Image(last_prediction["imagePath"], width=250, height=250))
        except:
            elements.append(Paragraph("⚠️ Image not available", styles['Normal']))
        elements.append(Spacer(1, 20))

    # التذييل
    elements.append(Paragraph("----", styles['Normal']))
    elements.append(Paragraph("Generated by Pneumonia Detector System", styles['Italic']))
    elements.append(Paragraph("This report is for educational/demo purposes only.", styles['Italic']))

    doc.build(elements)
    buffer.seek(0)

    return send_file(buffer, as_attachment=True, download_name="Medical_Report.pdf", mimetype='application/pdf')


if __name__ == '__main__':
    app.run(port=5000, debug=True)
